apiVersion: v2
name: deb-chart
description: A Helm chart for Debezium with Visual Connector
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: kafka
  version: 0.1.0
  repository: file://./charts/kafka
  condition: kafka.enabled
- name: zookeeper
  version: 0.1.0
  repository: file://./charts/zookeeper
  condition: zookeeper.enabled
- name: kafka-connect
  version: 0.1.0
  repository: file://./charts/kafka-connect
  condition: kafka-connect.enabled
- name: visual-connector
  version: 0.1.0
  repository: file://./charts/visual-connector
  condition: visual-connector.enabled
