## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
zookeeper:
  enabled: true
  servers: 2
  image: confluentinc/cp-zookeeper
  imageTag: 6.1.0
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    dataDirSize: 1Gi
    dataLogDirSize: 1Gi
  securityContext: 
    runAsUser: 0

  resources: {}
  ## If you do want to specify resources, uncomment the following lines, adjust them as necessary,
  ## and remove the curly braces after 'resources:'
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
kafka:
  enabled: true
  prometheus:
    jmx:
      enabled: false
  brokers: 3
  image: confluentinc/cp-enterprise-kafka
  imageTag: 6.1.0
  imagePullSecrets:
  heapOptions: "-Xms512M -Xms512M"
  configurationOverrides:
    "offsets.topic.replication.factor": 2
    "default.replication.factor": 2
    "auto.create.topics.enable": true
  persistence:
    enabled: true
    size: 1Gi
    disksPerBroker: 1
  resources: {}
  ## If you do want to specify resources, uncomment the following lines, adjust them as necessary,
  ## and remove the curly braces after 'resources:'
#    limits:
#      cpu: 300m
#      memory: 1024Mi
#    requests:
#      cpu: 300m
#      memory: 1024Mi
  securityContext: 
    runAsUser: 0

## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
kafka-connect:
  enabled: true
  prometheus:
    jmx:
      enabled: false
  replicaCount: 2
  heapOptions: "-Xms512M -Xmx512M"
  image: techbros8080/dbz-kafka-connect
  imageTag: 1.7
  configurationOverrides:
    "config.storage.replication.factor": "2"
    "offset.storage.replication.factor": "2"
    "status.storage.replication.factor": "2"
  resources: {}
  ## If you do want to specify resources, uncomment the following lines, adjust them as necessary,
  ## and remove the curly braces after 'resources:'
#    limits:
#      cpu: 500m
#      memory: 1024Mi
#    requests:
#      cpu: 500m
#      memory: 1024Mi
  securityContext: 
    runAsUser: 0

## ------------------------------------------------------
## Visual Connector
## ------------------------------------------------------
visual-connector:
  enabled: true
  replicaCount: 1
  image: techbros8080/dbz-nginx
  imageTag: 1.7
  imagePullPolicy: IfNotPresent
  httpPort: 80
  serviceHttpPort: 8084
  ## Visual Connector
  dbzVisualConnector:
    image: techbros8080/dbz-visual-connector
    imageTag: 1.7
    imagePullPolicy: IfNotPresent
    port: 3006
  ## Visual Connector
  dbzVisualConnectorBe:
    image: techbros8080/dbz-visual-connector-be
    imageTag: 1.7
    imagePullPolicy: IfNotPresent
    port: 3005
    volumeMounts:
      - name: storage
        mountPath: /app/store/
    volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: visual-connector-be-persistentvolumeclaim
  resources: {}
  ## If you do want to specify resources, uncomment the following lines, adjust them as necessary,
  ## and remove the curly braces after 'resources:'
#    limits:
#      cpu: 300m
#      memory: 256Mi
#    requests:
#      cpu: 300m
#      memory: 256Mi