# Default values for kafka-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceHttpPort: 8084
image: techbros8080/dbz-nginx
imageTag: 1.7
imagePullPolicy: IfNotPresent
httpPort: 80
## Visual Connector
dbzVisualConnector:
  image: techbros8080/dbz-visual-connector
  imageTag: 1.7
  imagePullPolicy: IfNotPresent
  port: 3006

## Visual Connector
dbzVisualConnectorBe:
  image: techbros8080/dbz-visual-connector-be
  imageTag: 1.7
  imagePullPolicy: IfNotPresent
  port: 3005
  volumeMounts:
    - name: storage
      mountPath: /app/store/
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: visual-connector-be-persistentvolumeclaim


## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
kafka-connect:
  enabled: true
  prometheus:
    jmx:
      enabled: false
  replicaCount: 2
  heapOptions: "-Xms512M -Xmx512M"
  image: techbros8080/dbz-kafka-connect
  imageTag: 1.7
  configurationOverrides:
    "config.storage.replication.factor": "2"
    "offset.storage.replication.factor": "2"
    "status.storage.replication.factor": "2"
  resources: {}
  ## If you do want to specify resources, uncomment the following lines, adjust them as necessary,
  ## and remove the curly braces after 'resources:'
#    limits:
#      cpu: 500m
#      memory: 1024Mi
#    requests:
#      cpu: 500m
#      memory: 1024Mi
  securityContext: 
    runAsUser: 0