# Default values for kafka-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceHttpPort: 8084
image: techbros8080/dbz-nginx
imageTag: 1.7
imagePullPolicy: IfNotPresent
httpPort: 80
## Visual Connector
dbzVisualConnector:
  image: techbros8080/dbz-visual-connector
  imageTag: 1.7
  imagePullPolicy: IfNotPresent
  port: 3006

## Visual Connector
dbzVisualConnectorBe:
  image: techbros8080/dbz-visual-connector-be
  imageTag: 1.7
  imagePullPolicy: IfNotPresent
  port: 3005
  volumeMounts:
    - name: storage
      mountPath: /app/store/
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: visual-connector-be-persistentvolumeclaim