{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "visual-connector.fullname" . }}
  labels:
    app: {{ template "visual-connector.name" . }}
    chart: {{ template "visual-connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "visual-connector.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "visual-connector.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "visual-connector.name" . }}-lb
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.httpPort }}
        - name: {{ template "visual-connector.name" . }}-ui
          image: "{{ .Values.dbzVisualConnector.image }}:{{ .Values.dbzVisualConnector.imageTag }}"
          imagePullPolicy: "{{ .Values.dbzVisualConnector.imagePullPolicy }}"
          ports:
          - containerPort: {{ .Values.dbzVisualConnector.port }}
        - name: {{ template "visual-connector.name" . }}-be
          image: "{{ .Values.dbzVisualConnectorBe.image }}:{{ .Values.dbzVisualConnectorBe.imageTag }}"
          imagePullPolicy: "{{ .Values.dbzVisualConnectorBe.imagePullPolicy }}"
          env:
          - name: KAFKA_CONNECT_SERVER
            value: "{{ template "visual-connector.kafka-connect.server" . }}"
          - name: KAFKA_CONNECT_PORT
            value: "{{ template "visual-connector.kafka-connect.servicePort" . }}"
          - name: KAFKA_CONNECT_DEFAULT_NAME
            value: "{{ template "visual-connector.kafka-connect.server" . }}"
          ports:
          - containerPort: {{ .Values.dbzVisualConnectorBe.port}}
          {{- if .Values.dbzVisualConnectorBe.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.dbzVisualConnectorBe.volumeMounts | indent 10 }}
          {{- end}}
          {{- if .Values.dbzVisualConnectorBe.volumes }}
      volumes:
{{ toYaml .Values.dbzVisualConnectorBe.volumes | trim | indent 6 }}
          {{- end}}